Linear Discriminant Analysis.

In [1]:
# Let initialize the positive and negative data matrices
import numpy as np
XP=np.asmatrix([[4,2,2,3,4,6,3,8],[1,4,3,6,4,2,2,3],[0,1,1,0,-1,0,1,0]])
XN=np.asmatrix([[9,6,9,8,10],[10,8,5,7,8],[1,0,0,1,-1]])

 1) Computing Class specific means of positive and negative training data

In [2]:
print("Mean of class 1:")
XPMean=np.asmatrix([np.mean(XP[i]) for i in range(3)])
print(XPMean.T)
print("\n")

print("Mean of class 2:")
XNMean=np.asmatrix([np.mean(XN[i]) for i in range(3)])
print(XNMean.T)

Mean of class 1:
[[4.   ]
 [3.125]
 [0.25 ]]


Mean of class 2:
[[8.4]
 [7.6]
 [0.2]]


2) Computing Class specific covariance matrices of positive and negative training data

In [3]:
temp=XP - XPMean.T
XPCov=np.zeros((3,3))
for i in range(8):
  XPCov=XPCov+np.dot(temp[:,i],temp[:,i].T)
print("Covariance matrix for positive training data:")
print(XPCov)

Covariance matrix for positive training data:
[[30.    -6.    -5.   ]
 [-6.    16.875 -1.25 ]
 [-5.    -1.25   3.5  ]]


In [4]:
temp=XN - XNMean.T
XNCov=np.zeros((3,3))
for i in range(5):
  XNCov=XNCov+np.dot(temp[:,i],temp[:,i].T)
print("Covariance matrix for negative training data:")
print(XNCov)

Covariance matrix for negative training data:
[[ 9.2 -0.2 -1.4]
 [-0.2 13.2  1.4]
 [-1.4  1.4  2.8]]


3) Computing the Between class scattering matrix 

In [5]:
temp=XPMean.T-XNMean.T
SB=np.dot(temp,temp.T)
print("Between class scattering matrix:")
print(SB)

Between class scattering matrix:
[[ 1.9360000e+01  1.9690000e+01 -2.2000000e-01]
 [ 1.9690000e+01  2.0025625e+01 -2.2375000e-01]
 [-2.2000000e-01 -2.2375000e-01  2.5000000e-03]]


4) Computing With in the class scattering matrix

In [6]:
# Sum of covariance matrices of two classes is with in class scattering matrix
SW=XPCov+XNCov
print("With in Class scattering matrix:")
print(SW)

With in Class scattering matrix:
[[39.2   -6.2   -6.4  ]
 [-6.2   30.075  0.15 ]
 [-6.4    0.15   6.3  ]]


5) Computing LDA Projection vector

In [7]:
A=np.array(np.dot(np.linalg.inv(SW),SB))
Eigval,Eigvec=np.linalg.eig(A)
indices=np.argsort(Eigval)
Eigval=[Eigval[i] for i in indices][::-1]
Eigvec=Eigvec.T
Eigvec=[Eigvec[i] for i in indices][::-1]
Eigvec=np.array(Eigvec)
print("Eigven values:")
print(Eigval)
print("\n")
print("Projection Vector(Eigen vector corresponding to largest eigen value):")
projVec=np.asmatrix(Eigvec[0])
print(projVec)

Eigven values:
[1.5419835521352048, 3.3306690738754696e-16, 3.469446951953614e-18]


Projection Vector(Eigen vector corresponding to largest eigen value):
[[0.56941154 0.62283144 0.53651793]]


6) Computing projection of positive and negative classes data onto vector

In [8]:
Xpprojec=np.dot(XP.T,projVec.T)
print("Projection of positive training data:")
print(Xpprojec)
xpmean=np.mean(Xpprojec)
Xnprojec=np.dot(XN.T,projVec.T)
print("Projection of negative training data:")
print(Xnprojec)
xnmean=np.mean(Xnprojec)
threshold=(xpmean+xnmean)/2.0

Projection of positive training data:
[[2.9004776 ]
 [4.16666679]
 [3.54383534]
 [5.44522329]
 [4.232454  ]
 [4.66213212]
 [3.49041544]
 [6.42378665]]
Projection of negative training data:
[[11.88953623]
 [ 8.39912079]
 [ 8.23886108]
 [ 9.45163036]
 [10.14024902]]


7) write mybLDA_train function to return projection direction

In [14]:
def mybLDA_train(XP,XN):
  # Get the dimensions of input matrices
  pdim=XP.shape[0]
  ndim=XN.shape[0]
  psam=XP.shape[1]
  nsam=XN.shape[1]
  # Compute the class specific means
  XPMean=np.asmatrix([np.mean(XP[i]) for i in range(pdim)])
  XNMean=np.asmatrix([np.mean(XN[i]) for i in range(ndim)])
  temp=XP - XPMean.T
  # Compute class specific covariance matrices
  XPCov=np.zeros((pdim,ndim))
  for i in range(psam):
    XPCov=XPCov+np.dot(temp[:,i],temp[:,i].T)
  temp=XN - XNMean.T
  XNCov=np.zeros((ndim,ndim))
  for i in range(nsam):
    XNCov=XNCov+np.dot(temp[:,i],temp[:,i].T)
  # Compute between the class and with in class scattering matrices
  temp=XPMean.T-XNMean.T
  SB=np.dot(temp,temp.T)
  SW=XPCov+XNCov
  # Compute Eigen values and vectors and return the vector corresponding to largest eigen value
  A=np.array(np.dot(np.linalg.inv(SW),SB))
  Eigval,Eigvec=np.linalg.eig(A)
  indices=np.argsort(Eigval)
  Eigval=[Eigval[i] for i in indices][::-1]
  Eigvec=Eigvec.T
  Eigvec=[Eigvec[i] for i in indices][::-1]
  Eigvec=np.array(Eigvec)
  projVec=np.asmatrix(Eigvec[0])

  return projVec
projectedVector=mybLDA_train(XP,XN)
print("Projected Direction: ")
print(projectedVector)

Projected Direction: 
[[0.56941154 0.62283144 0.53651793]]


8) write mybLDA_classify function to return classification data

In [17]:
def mybLDA_classify(X,v):
  projectedTestData=np.dot(X.T,v.T)
  print(threshold)
  xsam=X.shape[1]
  l=[]
  for i in projectedTestData:
    if i>threshold:
      l.append(-1)
    else:
      l.append(1)
  return l

9) Classify the given data

In [18]:
X=np.asmatrix([[1.3,2.4,6.7,2.2,3.4,3.2],[8.1,7.6,2.1,1.1,0.5,7.4],[-1,2,3,-2,0,2]])
projectedVector = mybLDA_train(XP,XN)
print(mybLDA_classify(X,projectedVector))

6.991001699616529
[1, -1, 1, 1, 1, -1]
