In [ ]:
import numpy as np
X=np.asmatrix([[-2,1,4,6,5,3,6,2],[9,3,2,-1,-4,-2,-4,5],[0,7,5,3,2,-3,4,6]])
X
#This is the data given

matrix([[-2,  1,  4,  6,  5,  3,  6,  2],
        [ 9,  3,  2, -1, -4, -2, -4,  5],
        [ 0,  7,  5,  3,  2, -3,  4,  6]])

Calculation of mean with Built In function

In [ ]:
Mean_1 = np.mean(X, axis=1)
Mean_1

matrix([[3.125],
        [1.   ],
        [3.   ]])

Calculation of mean with own code

In [ ]:
unitary=np.asmatrix([1,1,1,1,1,1,1,1]).T
Mean_2=np.dot(X,unitary)/8
Mean_2

matrix([[3.125],
        [1.   ],
        [3.   ]])

Calculation of centered matrix using python library

In [ ]:
X1 = X - np.mean(X, axis=1)
X1

matrix([[-5.125, -2.125,  0.875,  2.875,  1.875, -0.125,  2.875, -1.125],
        [ 8.   ,  2.   ,  1.   , -2.   , -5.   , -3.   , -5.   ,  4.   ],
        [-3.   ,  4.   ,  2.   ,  0.   , -1.   , -6.   ,  1.   ,  3.   ]])

Calculation of centered matrix by Own code

In [ ]:
unitary=np.asmatrix([1,1,1,1,1,1,1,1]).T
(X-(np.dot(X,unitary)/8))

matrix([[-5.125, -2.125,  0.875,  2.875,  1.875, -0.125,  2.875, -1.125],
        [ 8.   ,  2.   ,  1.   , -2.   , -5.   , -3.   , -5.   ,  4.   ],
        [-3.   ,  4.   ,  2.   ,  0.   , -1.   , -6.   ,  1.   ,  3.   ]])

Calculation of covariance matrix using python library

In [ ]:
C=np.cov(X1)
C

array([[  7.55357143, -11.14285714,   1.        ],
       [-11.14285714,  21.14285714,   2.28571429],
       [  1.        ,   2.28571429,  10.85714286]])

Calculation of Covariance Matrix using own code

In [ ]:
avg = []
X1=np.asarray(X1)
cov = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        var = 0
        for d in X1.T:
            var += (d[i]) * (d[j])
        var /= (7)
        cov[i, j] = var
cov

array([[  7.55357143, -11.14285714,   1.        ],
       [-11.14285714,  21.14285714,   2.28571429],
       [  1.        ,   2.28571429,  10.85714286]])

Computation of first principal component using python library

In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
pca = PCA(n_components=3)
pca.fit_transform(X.T)
print("Maximum eigen value: ")
print(max(pca.explained_variance_))
print("First principal component: ")
print(pca.components_[0])
#Printing the first principal component

Maximum eigen value: 
27.536048126623335
First principal component: 
[-0.4815633   0.87171689  0.09058943]


Computation of first principal component and principal value using own code

In [ ]:
#Compute eigen values and eigen vectors
W,V=np.linalg.eig(cov)
#Sort eigen vectors with respect to sorted eigen values
indices=np.argsort(W)
W=[W[i] for i in indices][::-1]
V=V.T
V=[V[i] for i in indices][::-1]
V=np.array(V)
print("Eigen values are: ")
print(W)
print("Principal components are: ")
print(V)
print("Largest Eigen value is: ")
print(max(W))
print("First Principal component is: ")
print(V[W.index(max(W))])

Eigen values are: 
[27.536048126623346, 11.121761314876663, 0.8957619870714342]
Principal components are: 
[[-0.4815633   0.87171689  0.09058943]
 [ 0.21661875  0.01823134  0.97608603]
 [ 0.84921912  0.48967058 -0.19760977]]
Largest Eigen value is: 
27.536048126623346
First Principal component is: 
[-0.4815633   0.87171689  0.09058943]


Computation of best 1D representation of data matrix using python library

In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
pca = PCA(n_components=3)
k=pca.fit_transform(X.T)
print("1D representation of matrix: ")
print(k.T[0])
#1D representation of data (Projected data)

1D representation of matrix: 
[ 9.16997879  3.12911351  0.63152786 -3.12792827 -5.35210509 -3.09849183
 -5.65248953  4.30039457]


Computation of best 1D representation of data matrix using Own code

In [ ]:
print("Add back mean: ")
print((k.T+Mean_1)[0])

Add back mean: 
[[ 1.22949788e+01  6.25411351e+00  3.75652786e+00 -2.92827459e-03
  -2.22710509e+00  2.65081696e-02 -2.52748953e+00  7.42539457e+00]]


In [ ]:
W,V=np.linalg.eig(cov)
indices=np.argsort(W)
W=[W[i] for i in indices][::-1]
V=V.T
V=[V[i] for i in indices][::-1]
V=np.array(V)
projected_data = np.dot(V,X1).T
projected_data.T[0]
#1D representation of data (Projected data)

array([ 9.16997879,  3.12911351,  0.63152786, -3.12792827, -5.35210509,
       -3.09849183, -5.65248953,  4.30039457])

In [ ]:
print("Add back mean: ")
print((projected_data.T+Mean_2)[0])

Add back mean: 
[[ 1.22949788e+01  6.25411351e+00  3.75652786e+00 -2.92827459e-03
  -2.22710509e+00  2.65081696e-02 -2.52748953e+00  7.42539457e+00]]


Implementation of My PCA

In [ ]:
import pandas as pd
import warnings
import numpy as np
def mypca(X,k):
  unitary=np.asmatrix([1,1,1,1,1,1,1,1]).T
  mean=np.dot(X,unitary)/8
  X1=(X-mean)
  avg=[]
  X1=np.asarray(X1)
  cov=np.zeros((k,k))
  for i in range(k):
    for j in range(k):
        temp=0
        for d in X1.T:
            temp+=d[i]*d[j]
        temp/=7
        cov[i,j]=temp
  eigval,eigvec=np.linalg.eig(cov)
  indices=np.argsort(eigval)
  eigval=[eigval[i] for i in indices][::-1]
  eigvec=eigvec.T
  eigvec=[eigvec[i] for i in indices][::-1]
  eigvec=np.array(eigvec)
  projected_data=np.dot(eigvec,X1).T
  return projected_data,eigvec,eigval
[rep,pc,pv]=mypca(X,3)
print("Data representation:")
print(rep)
print("Principal components:")
print(pc)
print("Principal values:")
print(pv)

Data representation:
[[ 9.16997879 -3.89257847  0.15794594]
 [ 3.12911351  3.48049195 -1.61568853]
 [ 0.63152786  2.1599448   0.83751777]
 [-3.12792827  0.58631623  1.46216381]
 [-5.35210509 -0.66108257 -0.65845727]
 [-3.09849183 -5.93828753 -0.38950552]
 [-5.65248953  1.50770824 -0.20445769]
 [ 4.30039457  2.75748735  0.4104815 ]]
Principal components:
[[-0.4815633   0.87171689  0.09058943]
 [ 0.21661875  0.01823134  0.97608603]
 [ 0.84921912  0.48967058 -0.19760977]]
Principal values:
[27.536048126623346, 11.121761314876663, 0.8957619870714342]


Computation of principal components using inbuilt PCA

In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
pca = PCA(n_components=3)
k=pca.fit_transform(X.T)
pri = pd.DataFrame(data = k, columns = ['principal component 1', 'principal component 2', 'principal component 3'])
print("Data Representtion:")
print(pri)
print("Principal components:")
print(pca.components_)
print("Principal values:")
print(pca.explained_variance_)

Data Representtion:
   principal component 1  principal component 2  principal component 3
0               9.169979               3.892578              -0.157946
1               3.129114              -3.480492               1.615689
2               0.631528              -2.159945              -0.837518
3              -3.127928              -0.586316              -1.462164
4              -5.352105               0.661083               0.658457
5              -3.098492               5.938288               0.389506
6              -5.652490              -1.507708               0.204458
7               4.300395              -2.757487              -0.410482
Principal components:
[[-0.4815633   0.87171689  0.09058943]
 [-0.21661875 -0.01823134 -0.97608603]
 [-0.84921912 -0.48967058  0.19760977]]
Principal values:
[27.53604813 11.12176131  0.89576199]
